version: "3.7"
services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: pizzeria
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            PGDATA: /var/lib/postgresql/data
        volumes:
        - "~/postgres_pizzeria:/var/lib/postgresql/pizzeria"
        ports:
        - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        environment:
          - PGADMIN_DEFAULT_EMAIL=admin@mail.com
          - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - "5050:80"